name: firefirestyle.cl.netbox
description: web client
version: 0.0.1
dependencies:
 firefirestyle.httprequest:
    git:
      url: https://github.com/firefirestyle/dart.httprequest.git
# firefirestyle.httprequest:
#    path: ../dart.httprequest
 firefirestyle.miniprop:
   git:
     url: https://github.com/firefirestyle/dart.miniprop.git
# firefirestyle.location:
#   git:
#     url: https://github.com/firefirestyle/dart.location.git
#
